return {
    "folke/snacks.nvim",
    priority = 1000,
    lazy = false,
    opts = {
        bigfile = { enabled = false },
        bufdelete = { enabled = false },
        dashboard = { enabled = false },
        debug = { enabled = false },
        dim = { enabled = false },
        explorer = { enabled = false },
        git = { enabled = false },
        gitbrowse = { enabled = false },
        image = { enabled = true },
        indent = { enabled = false },
        input = { enabled = true },
        layout = { enabled = false },
        lazygit = { enabled = false },
        notifier = { enabled = false },
        picker = { enabled = true },
        profiler = { enabled = false },
        quickfile = { enabled = false },
        -- TODO: Look into this
        rename = { enabled = false },
        scope = { enabled = false },
        scratch = { enabled = false },
        scroll = { enabled = false },
        statuscolumn = { enabled = false },
        terminal = { enabled = false },
        toggle = { enabled = false },
        win = { enabled = false },
        words = { enabled = false },
        zen = { enabled = false },
    },
    keys = {
        { "<leader>f",  function() Snacks.picker.smart() end, desc = "Find Files" },
        { "<leader>b",  function() Snacks.picker.buffers() end,    desc = "Search Buffers" },
        { "<leader>lg", function() Snacks.picker.grep() end,  desc = "Open LiveGrep" },
    }
}
